using System.Linq;
using System.Numerics;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Content.Shared._Starlight.Medical.HealthAnalyzer;
using Content.Shared.Mobs.Systems;

namespace Content.Client._Starlight.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class StarlightHealthAnalyzerControl : BoxContainer
{
    public bool TemperatureInKelvins { get; set; }

    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;
    private readonly MobThresholdSystem _threshold;

    // Printable health reports.
    public event Action? PrintReportPressed;
    /// <summary>
    /// Sets the print report button visible
    /// </summary>
    public void SetPrintReportVisible(bool visible) => PrintReportButton.Visible = visible;

    public StarlightHealthAnalyzerControl()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();

        _spriteSystem = _entityManager.System<SpriteSystem>();
        _threshold = _entityManager.System<MobThresholdSystem>();

        PrintReportButton.OnPressed += _ => PrintReportPressed?.Invoke();
    }

    /// <summary>
    /// Populates the health analyzer UI
    /// </summary>
    public void Populate(HealthAnalyzerUiState state)
    {
        var target = _entityManager.GetEntity(state.TargetEntity);

        PrintReportButton.Disabled = true;

        if (target == null
            || !_entityManager.TryGetComponent<DamageableComponent>(target, out var damageable))
        {
            // This part will never execute, since HealthAnalyzerSystem.UpdateScannedUser() does not send a message
            // for invalid targets. TODO will be fixed.

            NoPatientDataText.Visible = true;
            ChemicalsHeader.Visible = false;
            ChemicalsContainer.Visible = false;
            return;
        }

        NoPatientDataText.Visible = false;
        PrintReportButton.Visible = (state.EnablePrint ?? true);
        PrintReportButton.Disabled = !PrintReportButton.Visible || !(state.ScanMode ?? false) || !(state.CanPrint ?? false);

        FixedPoint2 deathValue = 200;
        if (_threshold.TryGetDeadThreshold(target.Value, out var threshold) && threshold.Value > FixedPoint2.Zero)
        {
            deathValue = threshold.GetValueOrDefault(200);
        }

        IReadOnlyDictionary<string, FixedPoint2> damagePerType = damageable.Damage.DamageDict;
        var sortedGroups = damageable.DamagePerGroup
            .OrderBy(g => HealthAnalyzerFormatting.GetDamageGroupSortKey(g.Key))
            .ThenBy(g => g.Key)
            .ToDictionary(g => g.Key, g => g.Value);

        DrawHeader(state, target.Value);
        DrawVitals(state, target.Value, damageable, deathValue);
        DrawAbnormalities(state);
        DrawDamageBreakdown(sortedGroups, damagePerType, deathValue);
        DrawChemicals(state.Chemicals);
    }

    private void DrawHeader(HealthAnalyzerUiState state, EntityUid target)
    {
        // Scan Mode
        ScanModeLabel.Text = state.ScanMode.HasValue
            ? state.ScanMode.Value
                ? Loc.GetString("health-analyzer-window-scan-mode-active")
                : Loc.GetString("health-analyzer-window-scan-mode-inactive")
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        ScanModeLabel.FontColorOverride = state.ScanMode.HasValue && state.ScanMode.Value ? Color.Green : Color.Red;

        // Patient Information
        SpriteView.SetEntity(target);
        SpriteView.Visible = state.ScanMode.HasValue && state.ScanMode.Value;
        NoDataTex.Visible = !SpriteView.Visible;

        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(_entityManager.HasComponent<MetaDataComponent>(target)
            ? Identity.Name(target, _entityManager)
            : Loc.GetString("health-analyzer-window-entity-unknown-text"));
        NameLabel.SetMessage(name);

        SpeciesLabel.Text =
            _entityManager.TryGetComponent<HumanoidAppearanceComponent>(target,
                out var humanoidAppearanceComponent)
                ? Loc.GetString(_prototypes.Index<SpeciesPrototype>(humanoidAppearanceComponent.Species).Name)
                : Loc.GetString("health-analyzer-window-entity-unknown-species-text");
    }

    private void DrawVitals(HealthAnalyzerUiState state, EntityUid target, DamageableComponent damageable, FixedPoint2 deathValue)
    {
        VitalsContainer.RemoveAllChildren();

        // Status
        if (_entityManager.TryGetComponent<MobStateComponent>(target, out var mobStateComponent))
        {
            AddToVitals(GenerateVitalsInformationBlock(new HealthAnalyzerVitalsBlockData
            {
                Name = Loc.GetString("starlight-health-analyzer-window-entity-status-text"),
                Value = HealthAnalyzerFormatting.GetStatusText(mobStateComponent.CurrentState),
                HasBar = false,
                ValueColor = HealthAnalyzerFormatting.GetStatusColor(mobStateComponent.CurrentState),
            }));
        }

        // Temp
        AddToVitals(GenerateVitalsInformationBlock(new HealthAnalyzerVitalsBlockData
        {
            Name = Loc.GetString("starlight-health-analyzer-window-entity-temperature-text"),
            Value = HealthAnalyzerFormatting.FormatTemperature(state.Temperature, TemperatureInKelvins),
            HasBar = false,
            ValueColor = Color.White,
        }));

        // Blood
        var bloodRatio = 0f;
        var color = Color.White;

        if (float.IsFinite(state.BloodLevel))
        {
            bloodRatio = Math.Clamp(state.BloodLevel, 0f, 1f);
            color = HealthAnalyzerFormatting.GetBloodLevelAccentColorUi(bloodRatio);
        }

        SpriteSpecifier? bleeding = state.Bleeding == true
            ? new SpriteSpecifier.Rsi(new ResPath("/Textures/Interface/Alerts/bleed.rsi"), "bleed10")
            : null;

        AddToVitals(GenerateVitalsInformationBlock(new HealthAnalyzerVitalsBlockData
        {
            Name = Loc.GetString("starlight-health-analyzer-window-entity-blood-level-text"),
            Value = HealthAnalyzerFormatting.FormatBloodLevel(state.BloodLevel),
            HasBar = true,
            BarRatio = bloodRatio,
            ValueColor = color,
            BarColor = color,
            Icon = bleeding,
        }));

        // Total Damage
        var totalDamage = damageable.TotalDamage;
        var ratio = CalculateDamageRatio(totalDamage, deathValue);

        AddToVitals(GenerateVitalsInformationBlock(new HealthAnalyzerVitalsBlockData
        {
            Name = Loc.GetString("starlight-health-analyzer-window-entity-damage-total-text"),
            Value = totalDamage.ToString(),
            HasBar = true,
            BarRatio = ratio,
            ValueColor = Color.White,
            BarColor = HealthAnalyzerFormatting.GetDamageSeverityColorUi(ratio),
        }));

        // external things
        var vitals = state.Extensions.GetValueOrDefault().Vitals;

        foreach (var vital in vitals.OrderBy(x => x.Name))
            AddToVitals(GenerateVitalsInformationBlock(vital));

        // prevent not even hooks counts causing the last item to fill two columns
        if (VitalsContainer.ChildCount > 0 && VitalsContainer.Children[VitalsContainer.ChildCount - 1] is BoxContainer { ChildCount: 1 } lastRow)
            lastRow.AddChild(new BoxContainer { HorizontalExpand = true });
    }

    private void DrawDamageBreakdown(Dictionary<string, FixedPoint2> groups,
        IReadOnlyDictionary<string, FixedPoint2> damageDict, FixedPoint2 deathValue)
    {
        GroupsContainer.RemoveAllChildren();

        var grid = new GridContainer
        {
            Columns = 2, HorizontalExpand = true, HSeparationOverride = 16, VSeparationOverride = 16
        };

        foreach (var group in groups)
        {
            grid.AddChild(GenerateDamageCategoryBlock(group.Key, group.Value, damageDict, deathValue));
        }

        GroupsContainer.AddChild(grid);
    }

    private BoxContainer GenerateDamageCategoryBlock(string categoryId, FixedPoint2 damageValue,
        IReadOnlyDictionary<string, FixedPoint2> damageDict, FixedPoint2 deathValue)
    {
        var block = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Top,
            SeparationOverride = 0,

        };

        var dmgRatio = CalculateDamageRatio(damageValue, deathValue);
        var progressBar = new ProgressBar
        {
            MinValue = 0,
            MaxValue = 1,
            Value = dmgRatio,
            MinHeight = 3,
            MaxHeight = 3,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 4),  // todo figure out the margins
        };

        progressBar.BackgroundStyleBoxOverride ??= new StyleBoxFlat(Color.FromHex("#525252"));
        progressBar.ForegroundStyleBoxOverride ??= new StyleBoxFlat();
        ((StyleBoxFlat)progressBar.ForegroundStyleBoxOverride!).BackgroundColor =
            HealthAnalyzerFormatting.GetDamageSeverityColorUi(dmgRatio);

        block.AddChild(progressBar);

        var groupHeader = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 4,
            Margin = new Thickness(0, 0, 0, 3),
        };

        groupHeader.AddChild(new TextureRect
        {
            SetSize = new Vector2(15, 15),
            Texture = GetTexture(categoryId.ToLowerInvariant()),
            VerticalAlignment = VAlignment.Center,
        });

        groupHeader.AddChild(new Label
        {
            Text = _prototypes.Index<DamageGroupPrototype>(categoryId).LocalizedName,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Left,
        });

        groupHeader.AddChild(new Label
        {
            Text = damageValue.ToString(),
            HorizontalAlignment = HAlignment.Right
        });

        block.AddChild(groupHeader);

        var group = _prototypes.Index<DamageGroupPrototype>(categoryId);
        var hasVisibleDamage = group.DamageTypes.Any(type =>
            damageDict.TryGetValue(type, out var amount) && amount > 0);

        // early return with label if no damage
        if (!hasVisibleDamage)
        {
            block.AddChild(new Label
            {
                Text = Loc.GetString("starlight-health-analyzer-window-damage-none"),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                StyleClasses = new StyleClassCollection("FontSmall"),
                FontColorOverride = Color.FromHex("#C7CED7"),
                Margin = new Thickness(19, 1, 0, 1),
            });
            return block;
        }

        foreach (var type in group.DamageTypes)
        {
            if (!damageDict.TryGetValue(type, out var typeAmount) || typeAmount <= 0)
                continue;

            var damageTypeName = _prototypes.Index<DamageTypePrototype>(type).LocalizedName;
            var typeId = type.ToString().ToLowerInvariant();

            var damageRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Margin = new Thickness(19, 1, 0, 1),
                SeparationOverride = 4
            };

            damageRow.AddChild(new TextureRect
            {
                SetSize = new Vector2(15, 15),
                Texture = GetTexture(typeId),
                VerticalAlignment = VAlignment.Center,
            });

            var typeLabel = new Label
            {
                Text = damageTypeName,
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                StyleClasses = new StyleClassCollection("FontSmall"),
                FontColorOverride = Color.FromHex("#C7CED7")
            };

            var amountLabel = new Label
            {
                Text = typeAmount.ToString(),
                HorizontalAlignment = HAlignment.Right,
                StyleClasses = new StyleClassCollection("FontSmall"),
                FontColorOverride = Color.FromHex("#C7CED7")
            };

            damageRow.AddChild(typeLabel);
            damageRow.AddChild(amountLabel);
            block.AddChild(damageRow);
        }

        return block;
    }

    private void DrawAbnormalities(HealthAnalyzerUiState state)
    {
        var abnormalities = state.Extensions?.Abnormalities is { } supplied
            ? new List<HealthAnalyzerAbnormalityData>(supplied)
            : new List<HealthAnalyzerAbnormalityData>();

        if (state.Unrevivable == true)
        {
            abnormalities.Add(new HealthAnalyzerAbnormalityData
            {
                Description = Loc.GetString("starlight-health-analyzer-window-entity-unrevivable-text"),
                Color = Color.FromHex("#EDE609")
            });
        }

        var showAlerts = abnormalities.Any();

        AbnormalitiesHeader.Visible = showAlerts;
        AbnormalitiesContainer.Visible = showAlerts;

        if (!showAlerts)
            return;

        AbnormalitiesContainer.RemoveAllChildren();

        foreach (var abnormality in abnormalities.OrderBy(x => x.Description))
        {
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 6,
            };

            var accent = new PanelContainer
            {
                MinWidth = 10,
                MaxWidth = 10,
                MinHeight = 16,
                VerticalAlignment = VAlignment.Stretch,
                PanelOverride = new StyleBoxFlat(abnormality.Color),
            };

            var description = new RichTextLabel
            {
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                Text = abnormality.Description,
            };

            row.AddChild(accent);
            row.AddChild(description);
            AbnormalitiesContainer.AddChild(row);
        }
    }

    private void DrawChemicals(List<(string ReagentId, FixedPoint2 Quantity, FixedPoint2 StomachQuantity)>? chemicals)
    {
        ChemicalsContainer.RemoveAllChildren();

        var hasChemicals = chemicals != null && chemicals.Count > 0;

        if (!hasChemicals || chemicals == null)
        {
            ChemicalsHeader.Visible = false;
            ChemicalsContainer.Visible = false;
            return;
        }

        ChemicalsHeader.Visible = true;
        ChemicalsContainer.Visible = true;

        var sortedReagents = chemicals.OrderByDescending(r => r.Quantity + r.StomachQuantity).ToList();

        foreach (var reagent in sortedReagents)
        {
            var reagentName = Loc.GetString("health-analyzer-window-entity-unknown-text");
            var reagentColor = Color.White;

            if (_prototypes.TryIndex<ReagentPrototype>(reagent.ReagentId, out var reagentProto))
            {
                reagentName = reagentProto.LocalizedName;
                reagentColor = reagentProto.SubstanceColor;
            }

            var rowContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Margin = new Thickness(0, 2),
            };

            // Color bar
            var colorBar = new PanelContainer
            {
                MinWidth = 10,
                MinHeight = 16,
                Margin = new Thickness(0, 0, 6, 0),
                PanelOverride = new StyleBoxFlat(reagentColor)
            };

            var nameLabel = new Label
            {
                Text = reagentName,
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left,
            };

            var quantityLabel = new RichTextLabel
            {
                HorizontalAlignment = HAlignment.Right,
            };

            var msg = new FormattedMessage();
            if (reagent.StomachQuantity > FixedPoint2.Zero && reagent.Quantity > FixedPoint2.Zero)
            {
                var formatted = Loc.GetString("health-analyzer-window-quantity-both", ("stomach", reagent.StomachQuantity), ("blood", reagent.Quantity));
                msg.AddMessage(FormattedMessage.FromMarkupOrThrow(formatted));
            }
            else if (reagent.StomachQuantity > FixedPoint2.Zero)
            {
                var formatted = Loc.GetString("health-analyzer-window-quantity-stomach", ("stomach", reagent.StomachQuantity));
                msg.AddMessage(FormattedMessage.FromMarkupOrThrow(formatted));
            }
            else if (reagent.Quantity > FixedPoint2.Zero)
            {
                var formatted = Loc.GetString("health-analyzer-window-quantity-blood", ("blood", reagent.Quantity));
                msg.AddMessage(FormattedMessage.FromMarkupOrThrow(formatted));
            }
            quantityLabel.SetMessage(msg);

            rowContainer.AddChild(colorBar);
            rowContainer.AddChild(nameLabel);
            rowContainer.AddChild(quantityLabel);
            ChemicalsContainer.AddChild(rowContainer);
        }
    }

    private BoxContainer GenerateVitalsInformationBlock(HealthAnalyzerVitalsBlockData data)
    {
        var container = new BoxContainer { Orientation = LayoutOrientation.Vertical, HorizontalExpand = true };
        var inner = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 8 };

        inner.AddChild(new Label { Text = data.Name, HorizontalAlignment = HAlignment.Left, HorizontalExpand = true });

        if (data.Icon is { } icon)
        {
            inner.AddChild(new TextureRect
            {
                Texture = _entityManager.System<SpriteSystem>().Frame0(icon),
                SetSize = new Vector2(15, 15),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                VerticalAlignment = VAlignment.Center
            });
        }

        inner.AddChild(new Label { Text = data.Value, FontColorOverride = data.ValueColor });

        container.AddChild(inner);

        if (data.HasBar)
        {
            var progressBar = new ProgressBar
            {
                MinValue = 0, MaxValue = 1, MinHeight = 3, MaxHeight = 3,
            };

            progressBar.BackgroundStyleBoxOverride ??= new StyleBoxFlat(Color.FromHex("#525252"));
            progressBar.ForegroundStyleBoxOverride ??= new StyleBoxFlat();

            ((StyleBoxFlat)progressBar.ForegroundStyleBoxOverride!).BackgroundColor = data.BarColor;

            progressBar.Value = data.BarRatio;

            container.SeparationOverride = 4;
            container.AddChild(progressBar);
        }

        return container;
    }

    private void AddToVitals(BoxContainer container)
    {
        BoxContainer? lastRow = null;

        if (VitalsContainer.ChildCount > 0)
        {
            lastRow = VitalsContainer.Children[VitalsContainer.ChildCount - 1] as BoxContainer;
        }

        if (lastRow is not { ChildCount: < 2 })
        {
            lastRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 16,
            };

            VitalsContainer.AddChild(lastRow);
        }

        lastRow.AddChild(container);
    }

    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/_Starlight/Objects/Devices/health_analyzer.rsi");
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);

        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out var state))
        {
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");
        }

        return _spriteSystem.Frame0(rsiSprite);
    }

    private float CalculateDamageRatio(FixedPoint2 current, FixedPoint2? deathValue) =>
        deathValue is { } maximum
            ? Math.Clamp((float)current / (float)maximum, 0f, 1f)
            : 0f;
}
