using System.Linq;
// Afterlight
using Content.Client.UserInterface.Controls;
// Afterlight
using Content.Shared._Starlight.Silicons.Borgs; // Starlight
// Afterlight
// Afterlight
using Content.Shared.Guidebook;
using Content.Shared.Silicons.Borgs;
using Content.Shared.Silicons.Borgs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Client.Players.PlayTimeTracking; // Starlight-edit
using Robust.Client.Player; // Starlight-edit

namespace Content.Client.Silicons.Borgs;

/// <summary>
/// Menu used by borgs to select their type.
/// </summary>
/// <seealso cref="BorgSelectTypeUserInterface"/>
/// <seealso cref="BorgSwitchableTypeComponent"/>
[GenerateTypedNameReferences]
public sealed partial class BorgSelectTypeMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entManager = default!; // Starlight-edit
    [Dependency] private IPlayerManager _playerManager = default!; // Starlight-edit
    [Dependency] private JobRequirementsManager _requirementsManager = default!; // Starlight-edit

    private BorgTypePrototype? _selectedBorgType;

    public event Action<ProtoId<BorgTypePrototype>, EntityPrototype?>? ConfirmedBorgType; // Starlight - carries the subtype

    private static readonly List<ProtoId<GuideEntryPrototype>> GuidebookEntries = new() { "Cyborgs", "Robotics" };

    public BorgSelectTypeMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

#region Starlight

        ConfirmTypeButton.OnPressed += ConfirmButtonPressed;
        HelpGuidebookIds = GuidebookEntries;

        // Afterlight - borg subtypes
        ChassisSpriteSelection.SubtypeSelected += () => ConfirmTypeButton.Disabled = false;
        // Afterlight end
    }

    // Move from BorgSelectTypeMenu to method
    public void SetupMenu(EntityUid owner)
    {
        // Available types
        if (!_entManager.TryGetComponent<BorgSwitchableTypeComponent>(owner, out var switchableType))
            return;

        var group = new ButtonGroup();
        // Available types
        if (switchableType.AvailableTypes.Any())
            foreach (var borgTypeId in switchableType.AvailableTypes)
            {
                if (!_prototypeManager.TryIndex<BorgTypePrototype>(borgTypeId, out var borgType))
                    continue;

                var button = new Button
                {
                    Text = PrototypeName(borgType),
                    Group = group,
                };
                button.OnPressed += _ =>
                {
                    //_selectedBorgType = borgType; Starlight: Already added at UpdateInformation
                    UpdateInformation(borgType);
                };
                button.Disabled = !_requirementsManager.CheckRequirementsForNonRole(borgType.Requirements, _playerManager.LocalSession, null, out _); // Starlight-edit
                SelectionsContainer.AddChild(button);
            }
        else
            foreach (var borgType in _prototypeManager.EnumeratePrototypes<BorgTypePrototype>().Where(p => p.ID != BorgChassisResetSystem.UnselectedType).OrderBy(PrototypeName)) // Starlight - the blank chassis type is not selectable
            {
                var button = new Button
                {
                    Text = PrototypeName(borgType),
                    Group = group,
                };
                button.OnPressed += _ =>
                {
                    //_selectedBorgType = borgType; Starlight: Already added at UpdateInformation
                    UpdateInformation(borgType);
                };
                button.Disabled = !_requirementsManager.CheckRequirementsForNonRole(borgType.Requirements, _playerManager.LocalSession, null, out _); // Starlight-edit
                SelectionsContainer.AddChild(button);
            }

    }
#endregion

    private void UpdateInformation(BorgTypePrototype prototype)
    {
        _selectedBorgType = prototype;

        InfoContents.Visible = true;
        InfoPlaceholder.Visible = false;
        // ConfirmTypeButton.Disabled = false; Starlight

        // Afterlight - borg subtype
        if (_selectedBorgType != null)
        {
            ChassisSpriteSelection.Update(_selectedBorgType);
            ConfirmTypeButton.Disabled = !ChassisSpriteSelection.HasSelection; // Starlight
        }
        // Afterlight end

        NameLabel.Text = PrototypeName(prototype);
        DescriptionLabel.Text = Loc.GetString($"borg-type-{prototype.ID}-desc");
        ChassisView.SetPrototype(prototype.DummyPrototype);
    }

    private void ConfirmButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        if (_selectedBorgType == null)
            return;

        ConfirmedBorgType?.Invoke(_selectedBorgType, ChassisSpriteSelection.SubtypePrototype); // Afterlight
    }

    private static string PrototypeName(BorgTypePrototype prototype)
    {
        return Loc.GetString($"borg-type-{prototype.ID}-name");
    }
}
