- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillLockerWarden
        - !type:NestedSelector
          tableId: FillLockerWardenHarduit

- type: entity
  id: LockerWardenFilled
  categories: [ ShouldMapStation ] # Starlight
  suffix: Filled
  parent: LockerWarden
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerWarden

- type: entityTable
  id: FillLockerWarden
  table: !type:AllSelector
    children:
    - id: ClothingEyesHudSecurity #Starlight
    - id: ClothingHeadsetSecurityWarden #Starlight
    - id: WeaponEnergyShotgun #Starlight
    - id: FlashlightSeclite
    - id: WeaponDisabler
    - id: WeaponTaser
    - id: ClothingBeltSecurityFilled
    - id: Flash
    - id: ClothingEyesGlassesSecurity
#    - id: ClothingHandsGlovesCombat # Starlight, they spawn with these now.
    - id: ClothingShoesBootsJack
    - id: ClothingOuterCoatWarden
    - id: ClothingOuterWinterWarden
    - id: DoorRemoteArmory
    - id: BoxWardenStamps #Starlight
    - id: HoloprojectorSecurity
    - id: BookSpaceLaw
    - id: ClothingBackpackElectropack
      amount: 2
    - id: RemoteSignaller
      amount: 2
    - id: NetworkConfigurator
    - id: Binoculars
    - id: NeuralLinkDisruptor # Starlight
    - id: TicketPad # Starlight
    - id: PlushieLizardJobWarden
      prob: 0.02

- type: entityTable
  id: FillLockerWardenHarduit
  table: !type:AllSelector
    children:
    - id: ClothingOuterHardsuitWarden
    - id: OxygenTankFilled
    - id: NitrogenTankFilled # Starlight - vox gang
    - id: CoolingUnit # Starlight - Beep, Boop!
    - id: ClothingMaskBreath

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerSecurity

- type: entityTable
  id: FillLockerSecurity
  table: !type:AllSelector
    children:
    - id: ClothingHandsGlovesSecurityRed #Starlight
    - id: ClothingEyesHudSecurity #Starlight
    - id: TicketPad # Starlight
    - id: FlashlightSeclite
      prob: 0.8
    - id: WeaponDisabler
    - id: WeaponTaser
    - id: ClothingUniformJumpsuitSecGrey
      prob: 0.3
    - id: ClothingHeadHelmetBasic
    - id: ClothingOuterArmorBasic
    - id: ClothingBeltSecurityFilled
    - id: Flash
      prob: 0.5
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHeadsetSecurity
    - id: ClothingHandsGlovesColorBlack
    - id: ClothingShoesBootsJack
    - id: WeaponMeleeNeedle
      prob: 0.1
    - id: HoloprojectorSecurity
      prob: 0.6
    - id: BookSpaceLaw
      prob: 0.5
    - id: PlushieLizardJobSecuritycadet
      prob: 0.02
    - id: PlushieLizardJobSecurityofficer
      prob: 0.02

- type: entity
  id: LockerBrigmedicFilled
  suffix: Brigmedic, Filled
  parent: LockerBrigmedic
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerBrigmedic

- type: entityTable
  id: FillLockerBrigmedic
  table: !type:AllSelector
    children:
    - id: ClothingEyesGlassesBrigmedic # Starlight
    - id: ClothingEyesGlassesCorpsman # Starlight
    - id: ClothingOuterCoatCorpsman #Starlight
    - id: ClothingUniformJumpsuitCorpsman #Starlight
    - id: ClothingUniformJumpskirtCorpsman #Starlight
    - id: ClothingHeadHatBeretCorpsman #Starlight
    - id: ClothingBeltCorpsmanFilled #Starlight
    - id: ClothingHandsGlovesBlackNitrile #Starlight
    - id: BottleCaseSecurityFilled # Starlight
    - id: PenPackSecurityFilled # Starlight
#    - id: ClothingEyesGlassesSecurity #Starlight, replacing with brigmed glasses.
    - id: WeaponTaser
    - id: WeaponDisabler
    - id: TrackingImplanter
      amount: 2
    - id: ClothingOuterHardsuitBrigmedic
    - id: ClothingShoesBootsMagSec # Starlight. They seem to have vanished.
    - id: RubberStampBrigmedic # Starlight. Also seems to have vanished.
    - id: BoxSterileMask
    - id: ClothingHeadHatBeretBrigmedic
    - id: ClothingOuterCoatAMG
    - id: ClothingUniformJumpsuitBrigmedic
    - id: ClothingUniformJumpskirtBrigmedic
    - id: ClothingUniformJumpskirtOfLife
      prob: 0.1
    - id: ClothingUniformJumpsuitOfLife # Starlight
      prob: 0.1 # Starlight
    - id: MedkitFilled
    - id: BedsheetBrigmedicStrange # Starlight
    - id: BedsheetBrigmedic # Starlight
    - !type:GroupSelector
      prob: 0.7
      children:
      - id: MedkitCombatFilled
        weight: 1.6
      - id: MedkitAdvancedFilled
      - id: MedkitOxygenFilled
        weight: 0.8
      - id: MedkitBruteFilled
        weight: 0.8
      - id: MedkitToxinFilled
        weight: 0.8
      - id: MedkitBurnFilled
        weight: 1.8
    - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
      prob: 0.15
    - id: JawsOfLifeMed #Starlight


- type: entity
  id: LockerDetectiveFilled
  categories: [ ShouldMapStation ] # Starlight
  suffix: Filled
  parent: LockerDetective
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerDetective

- type: entityTable
  id: FillLockerDetective
  table: !type:AllSelector
    children:
    - id: ClothingEyesGlassesNoir
    - id: WeaponEnergyMagnum #Starlight
    - id: ClothingHeadHatFedoraBrown #Starlight
    - id: ClothingHeadHatDetGadget
    - id: ClothingNeckTieDet
    - id: ClothingOuterVestDetective
    - id: ClothingOuterCoatDetectiveLoadout
    - id: FlippoEngravedLighter
    - id: FlashlightSeclite
    - id: ForensicScanner
    - id: LogProbeCartridge
    #- id: BoxForensicPad # Starlight - Condensing, duplicate of items found in the CardboardBoxLargeEvidenceFilledExtras
    - id: DrinkDetFlask
    - id: ClothingHandsGlovesForensic
    - id: RubberStampDetective
    - id: HoloprojectorSecurity
    #- id: BoxEvidenceMarkers # Starlight - Condensing, duplicate of items found in the CardboardBoxLargeEvidenceFilledExtras
    #- id: HandLabeler # Starlight - Condensing, duplicate of items found in the CardboardBoxLargeEvidenceFilledExtras
    - id: BoxTapeRecorder # Starlight
    - id: CardboardBoxLargeEvidenceFilledExtras # Starlight
    - id: PlushieLizardJobDetective
      prob: 0.02

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetBomb

- type: entityTable
  id: FillClosetBomb
  table: !type:AllSelector
    children:
    - id: ClothingHeadHelmetBombSuit
    - id: ClothingOuterSuitBomb
    - id: Wirecutter
    - id: Screwdriver
    - id: Multitool
      prob: 0.5

- type: entity
  parent: [GunSafeBaseSecuritySL, BaseSecurityContraband] #SL parenting
  id: GunSafeDisabler
  name: disabler safe
  components:
  #Starlight Start
  - type: EntityStorageVisuals
    stateDoorClosed: disabler_gunsafe_doors
  #Starlight End
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeDisabler

- type: entityTable
  id: FillGunSafeDisabler
  table: !type:AllSelector
    children:
    - id: WeaponDisabler
      amount: 5

- type: entity
  parent: [GunSafeBaseArmorySL, BaseSecurityContraband] #SL parenting
  id: GunSafePistolMk58
  name: pistol safe
  components:
  #Starlight Start
  - type: EntityStorageVisuals
    stateDoorClosed: pistol_gunsafe_doors
  #Starlight End
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafePistolMk58

- type: entityTable
  id: FillGunSafePistolMk58
  table: !type:AllSelector
    children:
    - id: BoxFiringPinPistol # Starlight, firing pins
    - id: WeaponPistolMk58
      amount: 2
    - id: WeaponPistolEnforcer
      amount: 1
    - id: MagazinePistolSP
      amount: 4
    - id: MagazinePistolHP
      amount: 2
    - id: MagazinePistolFMJ
      amount: 2

- type: entity
  parent: [GunSafeBaseArmorySL, BaseSecurityContraband] #SL parenting
  id: GunSafeRifleLecter
  name: rifle safe
  components:
  #Starlight Start
  - type: EntityStorageVisuals
    stateDoorClosed: lecter_gunsafe_doors
  #Starlight End
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeRifleLecter

- type: entityTable
  id: FillGunSafeRifleLecter
  table: !type:AllSelector
# Starlight-start
    children:
    - id: BoxFiringPin # Starlight, firing pins
    - id: WeaponRifleLecter
      amount: 2
    - id: WeaponRifleLeikha
      amount: 1
    - id: WeaponRifleLawbringer
      amount: 1
    - id: MagazineRifleHP
      amount: 4
    - id: MagazineRifleSP
      amount: 4
    - id: MagazineLightRifleSP
      amount: 1
    - id: MagazineLightRifleHP
      amount: 1
# Starlight-end

- type: entity
  parent: [GunSafeBaseArmorySL, BaseSecurityContraband] #SL parenting
  id: GunSafeSubMachineGunDrozd
  name: smg safe
  components:
  #Starlight Start
  - type: EntityStorageVisuals
    stateDoorClosed: drozd_gunsafe_doors
  #Starlight End
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeSubMachineGunDrozd

- type: entityTable
  id: FillGunSafeSubMachineGunDrozd
  table: !type:AllSelector
    children:
    - id: BoxFiringPinPistol # Starlight, firing pins
    - id: WeaponSubMachineGunDrozd
      amount: 2 # Starlight
    - id: WeaponSubMachineGunSP91RC
      amount: 2
    - id: MagazinePistolSubMachineGunSP
      amount: 5 # Starlight

- type: entity
  parent: [GunSafeBaseArmorySL, BaseSecurityContraband] #SL parenting
  id: GunSafeShotgunEnforcer
  name: heavy shotgun safe
  components:
  #Starlight Start
  - type: EntityStorageVisuals
    stateDoorClosed: enforcer_gunsafe_doors
  #Starlight End
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeShotgunEnforcer

- type: entityTable
  id: FillGunSafeShotgunEnforcer
  table: !type:AllSelector
    children:
    - id: BoxFiringPin # Starlight, firing pins
    - id: SpeedLoaderMagnumBasic
      amount: 2
    - id: WeaponShotgunEnforcer
      amount: 2
    - id: WeaponShotgunRiot
      amount: 1
    - id: BoxLethalshot
      amount: 4

- type: entity
  parent: [GunSafeBaseArmorySL, BaseSecurityContraband] #SL parenting
  id: GunSafeShotgunKammerer
  name: shotgun safe
  components:
  #Starlight Start
  - type: EntityStorageVisuals
    stateDoorClosed: kammerer_gunsafe_doors
  #Starlight End
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeShotgunKammerer

- type: entityTable
  id: FillGunSafeShotgunKammerer
  table: !type:AllSelector
    children:
    - id: BoxFiringPin # Starlight, firing pins
    - id: SpeedLoaderMagnumBasic
      amount: 2
    - id: WeaponShotgunKammerer
      amount: 2
    - id: WeaponShotgunRiot
      amount: 1
    - id: BoxLethalshot
      amount: 4

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: [GunSafeBaseArmorySL, BaseSecurityContraband] #SL parenting
  name: wt550 safe
  components:
  #Starlight Start
  - type: EntityStorageVisuals
    stateDoorClosed: wt550_gunsafe_doors
  #Starlight End
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeSubMachineGunWt550

- type: entityTable
  id: FillGunSafeSubMachineGunWt550
  table: !type:AllSelector
    children:
    - id: BoxFiringPinPistol # Starlight, firing pins
    - id: WeaponSubMachineGunWt550
      amount: 2
    - id: MagazinePistolSubMachineGunTopMounted
      amount: 4

- type: entity
  parent: [GunSafeBaseArmorySL, BaseSecurityContraband] #SL parenting
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  #Starlight Start
  - type: EntityStorageVisuals
    stateDoorClosed: laser_gunsafe_doors
  #Starlight End
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeLaserCarbine

- type: entityTable
  id: FillGunSafeLaserCarbine
  table: !type:AllSelector
    children:
    - id: BoxFiringPinLaser # Starlight, firing pins
    - id: WeaponLaserCarbine
      amount: 3
    - id: WeaponLr30
      amount: 1
    - id: MagazineBatteryLr30
      amount: 2
