- type: entity
  name: organ pod
  description: Strangest salad you've ever seen.
  parent: [FoodProduceBase, BaseSlicingRefinable]
  id: FoodOrganTree
  components:
    - type: FlavorProfile
      flavors:
        - strange
    - type: Sprite
      sprite: _Starlight/Objects/Specific/Hydroponics/organtree.rsi
      state: produce
    - type: Produce
      plantId: OrganTreePlants
    - type: ToolRefinable
      refineResult:
        - id: EffectOrganTree
    - type: Solution
      id: food
      solution:
        reagents:
          - ReagentId: Nutriment
            Quantity: 2
          - ReagentId: Vitamin
            Quantity: 2
    - type: Tag
      tags:
        - Fruit

- type: entity
  id: TrashMimanaPeelStealthy
  parent: TrashMimanaPeel
  name: mimana peel
  suffix: Stealthy
  components:
  - type: Stealth
    minVisibility: .15
    maxVisibility: 1
  - type: StealthOnMove
    passiveVisibilityRate: -0.37
    movementVisibilityRate: 0.50

- type: entity
  name: devilish apple
  parent: FoodProduceBase
  id: FoodEvilApple
  description: A fruit born of pure evil, eating it just might bring the doctors to you.
  components:
    - type: FlavorProfile
      flavors:
        - perfid
    - type: Solution
      id: food
      solution:
        reagents:
          - ReagentId: DevilJuice
            Quantity: 5
    - type: Sprite
      sprite: _Starlight/Objects/Specific/Hydroponics/evil_apple.rsi
    - type: Item
      heldPrefix: produce
    - type: Produce
      plantId: EvilApplePlants
    - type: Tag
      tags:
        - Fruit

- type: entity
  name: resinfera
  parent: FoodProduceBase
  id: FoodResinfera
  description: A plant used to nurse minor bruises, careful of the spines.
  components:
    - type: FlavorProfile
      flavors:
        - bitter
    - type: Solution
      id: food
      solution:
        reagents:
          - ReagentId: Acrileni
            Quantity: 5
    - type: Sprite
      sprite: _Starlight/Objects/Specific/Hydroponics/resinfera.rsi
    - type: Item
      heldPrefix: produce
    - type: Produce
      plantId: ResinferaPlants
    - type: Tag
      tags:
        - Fruit

- type: entity
  name: mint leaf
  parent: FoodProduceBase
  id: FoodMintLeaf
  description: A mint leaf to be made into mint extract, great for tea.
  components:
    - type: FlavorProfile
      flavors:
        - minty
    - type: Extractable
      juiceSolution:
        reagents:
        - ReagentId: MintExtract
          Quantity: 10
    - type: Solution
      id: food
      solution:
        reagents:
          - ReagentId: Nutriment
            Quantity: 5
    - type: Sprite
      sprite: _Starlight/Objects/Specific/Hydroponics/mint.rsi
    - type: Item
      heldPrefix: produce
    - type: Produce
      plantId: MintPlants
    - type: Tag
      tags:
        - Vegetable

- type: entity
  name: spearmint
  parent: Spear
  id: SpearMint
  description: A spear cut from a mutated mint plant.
  components:
  - type: Sprite
    sprite: _Starlight/Objects/Weapons/Melee/spearmint.rsi
  - type: Produce
    plantId: SpearMintPlants
  - type: MeleeWeapon
    wideAnimationRotation: -135
    damage:
      types:
        Piercing: 12
  - type: DamageOtherOnHit
    damage:
      types:
        Piercing: 12

- type: entity
  name: cinnamon stick
  parent: FoodProduceBase
  id: FoodCinnamonStick
  description: Dried bark rolled into a cinnamon stick, ready to bring the spice.
  components:
    - type: FlavorProfile
      flavors:
        - cinnamon
    - type: Solution
      id: food
      solution:
        reagents:
          - ReagentId: Cinnamon
            Quantity: 5
    - type: Sprite
      sprite: _Starlight/Objects/Specific/Hydroponics/cinnamon.rsi
    - type: Item
      heldPrefix: produce
    - type: Produce
      plantId: CinnamonPlants
    - type: Tag
      tags:
        - Vegetable

- type: entity
  name: cinnaflare stick
  parent: Flare
  id: CinnaflareStick
  description: Dried bark rolled into a stick, ready to ignite and light the way.
  components:
    - type: PotencyVisuals
    - type: Extractable
      grindableSolutionName: food
    - type: Solution
      id: flare
      solution:
        maxVol: 5
        reagents:
          - ReagentId: Oil
            Quantity: 5
    - type: ExpendableLight
      glowDuration: 145
      fadeOutDuration: 15
      plantBurnTimeModifier: 3
      iconStateOn: flare_unlit
      iconStateSpent: flare_spent
      turnOnBehaviourID: turn_on
      fadeOutBehaviourID: fade_out
      litSound:
        path: /Audio/Items/Flare/flare_on.ogg
      loopedSound:
        path: /Audio/Items/Flare/flare_burn.ogg
        params:
          loop: true
          volume: -10
          maxDistance: 5
    - type: Sprite
      sprite: _Starlight/Objects/Tools/cinnaflare.rsi
    - type: Item
      heldPrefix: unlit
    - type: Produce
      plantId: CinnaflarePlants
