- type: job
  id: SalvageLead
  name: job-name-salvagelead
  description: job-description-salvagelead
  rules: job-rules-itg-aligned
  playTimeTracker: JobSalvageLead
  supervisors: job-supervisors-guild
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 5h # 5 hours
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 18000 # 5 hours
  icon: "JobIconSalvageLead"
  startingGear: SalvageLeadGear
  displayWeight: 5
  access:
  - Salvage
  - SalvageLead
  - External
  - Maintenance
  - Shuttle
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: NoObjectiveTarget

- type: startingGear
  id: SalvageLeadGear
  equipment:
    ears: ClothingHeadsetSalvageLead
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: SalvageLeadChameleonOutfit
  job: SalvageLead
  equipment:
    head: ClothingHeadHatCargosoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGasExplorer
    outerClothing: ClothingOuterWinterMiner
    neck: ClothingNeckScarfStripedBrown
    gloves: ClothingHandsGlovesColorBlack
